language: d
dist: xenial
d:
  - dmd
  - ldc
  - gdc
matrix:
  allow_failures:
    - d: gdc
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # gcc-8 necessary as compatibility for spirv_cross-d
      - gcc-8
      - libwayland-dev
      - libx11-xcb-dev
script:
  - dub test --compiler=${DC}
  - DC=${DC} ./tools/build_examples.sh
